name: /sBin
lsi: false
highlighter: pygments
markdown: kramdown
timezone: Asia/Tehran
permalink: /blog/:year/:month/:day/:title
excerpt_separator: "\n\n"
exclude: [ .DS_Store ]
gems:
  - jekyll-redirect-from
  - jemoji
  - jekyll-mentions
